# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "3-security" ]
  pull_request:
    branches: [ "3-security" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Set up Yarn cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-yarn-${{ hashFiles('graylog2-web-interface/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
        path: ~/.cache/yarn
    - name: License check
      run: mvn -B --fail-fast license:check
    - name: Build with Maven
      run: mvn -B -Pedantic -DskipITs -Dskip.web.build=true -Dspotbugs.skip -Dit.es -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 verify javadoc:javadoc
      env:
        JAVA_OPTS: -Xmx6G
        TIMEOUT_MULTIPLIER: 2.0
    - name: Store build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifacts
        path: /home/runner/work/graylog2-server/graylog2-server/target/assembly/*.tar.gz
