# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release assets

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Set version
      run: sh set_version.sh "${{ github.ref_name }}"

    - name: Set up Yarn cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-yarn-${{ hashFiles('graylog2-web-interface/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
        path: ~/.cache/yarn

    - name: License check
      run: mvn -B --fail-fast license:check
    - name: Build with Maven
      run: mvn -B -Pedantic -Dmaven.test.skip=true -DskipITs -Dskip.web.build=true -Dspotbugs.skip -Dit.es -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 verify javadoc:javadoc
      env:
        JAVA_OPTS: -Xmx6G
        TIMEOUT_MULTIPLIER: 2.0

    - name: Prepare assets
      run: |
        cp /home/runner/work/graylog2-server/graylog2-server/target/assembly/graylog*.tar.gz "graylog2-${{ github.ref_name }}.tar.gz"
        sha256sum "graylog2-${{ github.ref_name }}.tar.gz" > "graylog2-${{ github.ref_name }}.tar.gz.sha256"

    - name: Upload asset SHA256 checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: "./graylog2-${{ github.ref_name }}.tar.gz.sha256"
        asset_name: "graylog2-${{ github.ref_name }}.tar.gz.sha256"
        asset_content_type: plain/text
    - name: Upload asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: "./graylog2-${{ github.ref_name }}.tar.gz"
        asset_name: "graylog2-${{ github.ref_name }}.tar.gz"
        asset_content_type: application/gzip
